### ISSUE TITLE
Just a note, don't know if you want to add it.

### ISSUE THREAD

**Issue by flamingbear** [p-madden/sea-2016-tutorial#18]
Here's what happens when you call a m(lats, lons) after creating a basemap projection

     Calling a Basemap class instance with the arguments lon, lat will
     convert lon/lat (in degrees) to x/y map projection coordinates
     (in meters). The inverse transformation is done if the optional keyword
     ``inverse`` is set to True.

**Comment by p-madden** [comment]
I worked in some text along these lines.
