### ISSUE TITLE
Something I'm unsure about....

### ISSUE THREAD

**Issue by flamingbear** [p-madden/sea-2016-tutorial#31]
```
Coordinates:
  * time                  (time) datetime64[ns] 1966-10-10 1966-10-17 ...
    snow_cover_threshold  float32 0.42
    latitude              (rows, cols) float64 0.6592 1.322 1.984 2.646 ...
    longitude             (rows, cols) float64 145.0 144.3 143.7 143.0 142.2 ...
  * cols                  (cols) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 ...
  * rows                  (rows) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 ...
```
When you examine an xarray.Dataset  The coordinates with asterisks are?  (probably the actual dimensions from the netcdf file)
```
dimensions:
	cols = 88 ;
	rows = 88 ;
	time = UNLIMITED ; // (2574 currently)
```

Ok, as I'm typing this, I'm finding I think I do understand it.

All of these variables in the file are references from another variable's `variable.coordinates` attribute

the ncdump output for snow_cover_extent is

```
	byte snow_cover_extent(time, rows, cols) ;
		snow_cover_extent:long_name = "NOAA/NCDC Climate Data Record of snow cover extent" ;
		snow_cover_extent:standard_name = "surface_snow_binary_mask" ;
		snow_cover_extent:grid_mapping = "coord_system" ;
		snow_cover_extent:coordinates = "longitude latitude time snow_cover_threshold" ;
		snow_cover_extent:valid_range = 0b, 1b ;
		snow_cover_extent:flag_values = 0b, 1b ;
		snow_cover_extent:flag_meanings = "no_snow snow_covered" ;
		snow_cover_extent:_FillValue = -9b ;

```

So you see `longitude` `latitude` `time` and `snow_cover_threshold` all as coordinates.

But I'm still not sure about the asterisks.

`cols` and `rows` are just dimensions, not variables.  `time` is a dimension that also has a variable that defines it.
??

Under data variables, what's with `coord_system`?

```
Data variables:
    coord_system          |S1 b''
    land                  (rows, cols) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0 ...
    area                  (rows, cols) float64 1.068e+04 1.092e+04 1.117e+04 ...
    snow_cover_extent     (time, rows, cols) float64 0.0 0.0 0.0 0.0 0.0 0.0 ...
```

I think it's a char variable, that by convention, has no data but only metadata.

ncdump:
```
char coord_system ;
		coord_system:grid_mapping_name = "latitude_longitude" ;
		coord_system:longitude_of_central_meridian = 0. ;
		coord_system:semimajor_axis = 6378137 ;
		coord_system:semiminor_axis = 6356752.3 ;
```

**Comment by p-madden** [comment]
Do the asterisks maybe indicate the arrays that xarray has decided to use as indices? When we do `dataset.indexes`, time, rows and cols are shown as the indexes.

**Comment by flamingbear** [comment]
that too.  But why?  because they are the dimensions that all of the variables are defined by?

**Comment by flamingbear** [comment]
And I guess dataset.data_vars is whatever netcdf variable is left in the file after pulling out any referenced by the dimensions, or the `coordinates`

**Comment by p-madden** [comment]
Here's the explanation, I think, about the asterisks: https://github.com/pydata/xarray/issues/234
