### ISSUE TITLE
ts.idxmax()

### ISSUE THREAD

**Issue by michael-brandt-cu** [p-madden/sea-2016-tutorial#35]
module 4

`ts.idxmax()` is another option for finding the time of the max value, as opposed to 

```
ts[ts == ts.max()]
```

**Comment by michael-brandt-cu** [comment]
You can then get the max value with `ts[ts.idxmax()]`

**Comment by flamingbear** [comment]
should probably be `ts.loc[ts.idxmax()]` ?

Maybe put both in.  There's lots of ways to get your data?

**Comment by michael-brandt-cu** [comment]
> There's lots of ways to get your data?

Pretty much this

**Comment by flamingbear** [comment]
Try things until you get what you want is how I usually operate

**Comment by p-madden** [comment]
I don't want to add more. Please re-open if you strongly disagree.
