### ISSUE TITLE
plotly for anaconda installs needs nsidc's channel.

### ISSUE THREAD

**Issue by flamingbear** [p-madden/sea-2016-tutorial#37]
Ran into the problem where someone who wasn't using the VM had a problem installing plotly with conda.  i pointed him to our channel, but the docs should be updated to reflect that (or install via pip)

**Comment by p-madden** [comment]
The module-0 docs specify "pip install plotly". Is that not correct / sufficient?

**Comment by flamingbear** [comment]
No that's sufficient, I didn't see it and the guy I was helping didn't either.
